@base = http://localhost:3000

# 获取所有用户

GET {{base}}/user

###

# 删除单个用户
DELETE {{base}}/user/1

###

# 新增用户

POST {{base}}/user
Content-Type: application/json

{
  "name": "test",
  "password": "123456"
}

###

# 登录
POST {{base}}/login
Content-Type: application/json

{
  "name": "test",
  "password": "123456"
}

###

# 获取登录信息
GET {{base}}/login/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb2xsb3dlcnMiOltdLCJyZWNvcmRzIjpbXSwibm90ZSI6IiIsImlkIjoyLCJjcmVhdGVkX2F0IjoiMjAyMi0wNS0yM1QxMzo1Njo1OC4xODJaIiwidXBkYXRlZF9hdCI6IjIwMjItMDUtMjNUMTM6NTY6NTguMTgyWiIsIm5hbWUiOiJ0ZXN0IiwiaWF0IjoxNjUzMzE2MTk2LCJleHAiOjE2NTMzMTk3OTZ9.jTp7OaMdJRSTWY0wAzGYjDJvZjJk_GaR2Kp5ups6OCI